Intex/Intex/Models/Invoice_Details.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Intex.Models
{
    [Table("Invoice_Details")]
    public class Invoice_Details
    {
        [Key]
        public int invoiceLine { get; set; }
        public decimal totalPrice { get; set; }

        [ForeignKey("Invoice")]
        public virtual int invoiceID { get; set; }
        public virtual Invoice Invoice { get; set; }

        [ForeignKey("Test")]
        public virtual int testID { get; set; }
        public virtual Test Test { get; set; }
    }
}

Intex/Intex/Controllers/AccountsRecController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Intex.DAL;
using Intex.Models;

namespace Intex.Controllers
{
    public class AccountsRecController : Controller
    {
        private IntexContext db = new IntexContext();

        // GET: AccountsRec
        public ActionResult ViewInvoice()
        {
            var invoices = db.Invoices.Include(i => i.Credit_Card_Payment).Include(i => i.Order).Include(i => i.Payment_Type);
            return View(invoices.ToList());
        }

        // GET: AccountsRec/Details/5
        public ActionResult InvoiceDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }

        // GET: AccountsRec/Create
        public ActionResult CreateInvoice()
        {
            ViewBag.creditCardPaymentNum = new SelectList(db.Credit_Card_Payments, "creditCardPaymentNum", "creditCardPaymentNum");
            ViewBag.orderID = new SelectList(db.Orders, "orderID", "comment");
            ViewBag.paymentTypeCode = new SelectList(db.Payment_Types, "paymentTypeCode", "paymentDescription");
            return View();
        }

        // POST: AccountsRec/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateInvoice([Bind(Include = "invoiceID,paymentDue,paymentEarly,earlyPaymentDisc,orderID,paymentTypeCode,creditCardPaymentNum")] Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                db.Invoices.Add(invoice);
                db.SaveChanges();
                return RedirectToAction("ViewInvoice");
            }

            ViewBag.creditCardPaymentNum = new SelectList(db.Credit_Card_Payments, "creditCardPaymentNum", "creditCardPaymentNum", invoice.creditCardPaymentNum);
            ViewBag.orderID = new SelectList(db.Orders, "orderID", "comment", invoice.orderID);
            ViewBag.paymentTypeCode = new SelectList(db.Payment_Types, "paymentTypeCode", "paymentDescription", invoice.paymentTypeCode);
            return View(invoice);
        }

        // GET: AccountsRec/Edit/5
        public ActionResult EditInvoice(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            ViewBag.creditCardPaymentNum = new SelectList(db.Credit_Card_Payments, "creditCardPaymentNum", "creditCardPaymentNum", invoice.creditCardPaymentNum);
            ViewBag.orderID = new SelectList(db.Orders, "orderID", "comment", invoice.orderID);
            ViewBag.paymentTypeCode = new SelectList(db.Payment_Types, "paymentTypeCode", "paymentDescription", invoice.paymentTypeCode);
            return View(invoice);
        }

        // POST: AccountsRec/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditInvoice([Bind(Include = "invoiceID,paymentDue,paymentEarly,earlyPaymentDisc,orderID,paymentTypeCode,creditCardPaymentNum")] Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                db.Entry(invoice).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ViewInvoice");
            }
            ViewBag.creditCardPaymentNum = new SelectList(db.Credit_Card_Payments, "creditCardPaymentNum", "creditCardPaymentNum", invoice.creditCardPaymentNum);
            ViewBag.orderID = new SelectList(db.Orders, "orderID", "comment", invoice.orderID);
            ViewBag.paymentTypeCode = new SelectList(db.Payment_Types, "paymentTypeCode", "paymentDescription", invoice.paymentTypeCode);
            return View(invoice);
        }

        // GET: AccountsRec/Delete/5
        public ActionResult DeleteInvoice(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }

        // POST: AccountsRec/Delete/5
        [HttpPost, ActionName("DeleteInvoice")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Invoice invoice = db.Invoices.Find(id);
            db.Invoices.Remove(invoice);
            db.SaveChanges();
            return RedirectToAction("ViewInvoice");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult QuerySales()
        {
            //choose which query to see
            //add date?
            return View();
        }

        public ActionResult ViewSales()
        {
                ViewBag.decision = 1;
                IEnumerable<Sales_Report_By_Customer> sales_Report_ByCustomer =
                db.Database.SqlQuery<Sales_Report_By_Customer>(
                    "use intex " +
                    "select clientFirstName, clientLastName, basePrice, testPrice " +
                    "from client " +
                    "left join [order] on client.clientid = [order].clientID " +
                    "left join test_result on Test_Result.orderID = [order].orderID " +
                    "left join test on test.testid = Test_Result.testID " +
                    "where basePrice is not null"
                    );
                return View(sales_Report_ByCustomer);
            
        }
    }
}

Intex/Intex/Views/AccountsRec/CreateInvoice.cshtml
@model Intex.Models.Invoice

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Invoice</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            Payment Due Date
            <div class="col-md-10">
                @Html.EditorFor(model => model.paymentDue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.paymentDue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Early Payment Date
            <div class="col-md-10">
                @Html.EditorFor(model => model.paymentEarly, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.paymentEarly, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Early Payment Discount
            <div class="col-md-10">
                @Html.EditorFor(model => model.earlyPaymentDisc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.earlyPaymentDisc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Comments
            <div class="col-md-10">
                @Html.DropDownList("orderID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.orderID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Payment Method
            <div class="col-md-10">
                @Html.DropDownList("paymentTypeCode", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.paymentTypeCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Credit Card Number
            <div class="col-md-10">
                @Html.DropDownList("creditCardPaymentNum", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.creditCardPaymentNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ViewInvoice")
</div>

Intex/Intex/Views/AccountsRec/DeleteInvoice.cshtml
@model Intex.Models.Invoice

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Invoice</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Credit Card Number
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Credit_Card_Payment.creditCardPaymentNum)
        </dd>

        <dt>
            Comments
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order.comment)
        </dd>

        <dt>
            Payment Method
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Payment_Type.paymentDescription)
        </dd>

        <dt>
            Payment Due Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.paymentDue)
        </dd>

        <dt>
            Payment Early Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.paymentEarly)
        </dd>

        <dt>
            Early Payment Discount
        </dt>

        <dd>
            @Html.DisplayFor(model => model.earlyPaymentDisc)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "ViewInvoice")
        </div>
    }
</div>

Intex/Intex/Views/AccountsRec/EditInvoice.cshtml
@model Intex.Models.Invoice

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Invoice</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.invoiceID)

        <div class="form-group">
            Payment Due Date
            <div class="col-md-10">
                @Html.EditorFor(model => model.paymentDue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.paymentDue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Payment Early Date
            <div class="col-md-10">
                @Html.EditorFor(model => model.paymentEarly, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.paymentEarly, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Early Payment Discount
            <div class="col-md-10">
                @Html.EditorFor(model => model.earlyPaymentDisc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.earlyPaymentDisc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Comments
            <div class="col-md-10">
                @Html.DropDownList("orderID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.orderID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Payment Method
            <div class="col-md-10">
                @Html.DropDownList("paymentTypeCode", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.paymentTypeCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Credit Card Number
            <div class="col-md-10">
                @Html.DropDownList("creditCardPaymentNum", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.creditCardPaymentNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ViewInvoice")
</div>

Intex/Intex/Views/AccountsRec/InvoiceDetails.cshtml
@model Intex.Models.Invoice

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Invoice</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Credit Card Number
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Credit_Card_Payment.creditCardPaymentNum)
        </dd>

        <dt>
            Comments
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order.comment)
        </dd>

        <dt>
            Payment Method
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Payment_Type.paymentDescription)
        </dd>

        <dt>
            Payment Due Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.paymentDue)
        </dd>

        <dt>
            Payment Early Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.paymentEarly)
        </dd>

        <dt>
            Early Payment Discount
        </dt>

        <dd>
            @Html.DisplayFor(model => model.earlyPaymentDisc)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "EditInvoice", new { id = Model.invoiceID }) |
    @Html.ActionLink("Back to List", "ViewInvoice")
</p>

Intex/Intex/Views/AccountsRec/QuerySales.cshtml
@{
    ViewBag.Title = "QuerySales";
}

<h2>Report Credentials</h2>
<br />
<h3>Select Report Type:</h3>
@Html.ActionLink("View Sales by client", "ViewSales", null, new { @class = "btn btn-warning" })
@Html.ActionLink("View Sales by assay", "ViewSales", null, new { @class = "btn btn-warning" })
@Html.ActionLink("View Sales by employee", "ViewSales", null, new { @class = "btn btn-warning" })

<hr />
<br />
@Html.ActionLink("Back to Dashboard", "Display", "Orders", null, new { @class = "btn btn-danger btn-md" })

Intex/Intex/Views/AccountsRec/ViewInvoice.cshtml
@model IEnumerable<Intex.Models.Invoice>

@{
    ViewBag.Title = "Index";
}

<h2>All Invoices</h2>

<p>
    @Html.ActionLink("Create New", "CreateInvoice")
</p>
<p>@Html.ActionLink("Back to Dashboard", "Display", "Orders", null, new { @class = "btn btn-danger btn-md" })</p>
<table class="table">
    <tr>
        <th>
            Credit Card Number
        </th>
        <th>
            Comments
        </th>
        <th>
            Payment Method
        </th>
        <th>
            Payment Due Date
        </th>
        <th>
           Payment Early Date
        </th>
        <th>
            Early Payment Discount
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Credit_Card_Payment.creditCardPaymentNum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Order.comment)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Payment_Type.paymentDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.paymentDue)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.paymentEarly)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.earlyPaymentDisc)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditInvoice", new { id=item.invoiceID }, new { @class = "btn btn-danger btn-sm" }) |
            @Html.ActionLink("Delete", "DeleteInvoice", new { id=item.invoiceID }, new { @class = "btn btn-danger btn-sm" })
        </td>
    </tr>
}

</table>

Intex/Intex/Views/AccountsRec/ViewSales.cshtml
@model IEnumerable<Intex.Models.Sales_Report_By_Customer>

@{
    ViewBag.Title = "ViewSales";
}

<h2>View Sales By Customer</h2>

<table class="table">
    <tr>
        <th>
            Client Name
        </th>
        <th>
            Total Income from Base Price
        </th>
        <th>
            Total Income from Tests
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.clientFirstName) @Html.DisplayFor(modelItem => item.clientLastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.basePrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.testPrice)
            </td>
        </tr>
    }

</table>

@Html.ActionLink("Back", "QuerySales", "AccountsRec", null, new { @class = "btn btn-danger btn-md" })